name: deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main", "feature/ci"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      # 도커허브 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      # 도커 이미지 생성 및 도커허브 업로드
      - name: Create docker image and Upload to DockerHub
        env:
          NAME: ${{secrets.DOCKER_HUB_NAME}}
          REPO: moi
          IMAGE: moi
        run: |
          docker build -f ./dockerfile -t $IMAGE .
          docker tag $IMAGE:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:latest

      # ssh 접속 및 shell 실행
#       - name: executing remote ssh commands using password
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.NCP_DEV_HOST }}
#           username: ${{ secrets.NCP_DEV_USERNAME }}
#           password: ${{ secrets.NCP_DEV_PASSWORD }}
#           script: |
#             ./imhero.sh
